services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - '4200:80'
    depends_on:
      - backend